name       : haskell-kan-extensions
version    : 5.0.1
release    : 1
source     :
    - https://hackage.haskell.org/package/kan-extensions-5.0.1/kan-extensions-5.0.1.tar.gz : 01de9fe57064a125ecb1d1161519df27043c2058ca246bbd5cd2d73c899ba0e2
license    : BSD-3-Clause
component  : programming.haskell
summary    : Kan extensions, Kan lifts, various forms of the Yoneda lemma, and (co)density (co)monads
description: |
    Kan extensions, Kan lifts, various forms of the Yoneda lemma, and (co)density (co)monads
builddeps  :
    - haskell-adjunctions
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
