name       : haskell-kan-extensions
version    : '5.1'
release    : 4
source     :
    - https://hackage.haskell.org/package/kan-extensions-5.1/kan-extensions-5.1.tar.gz : 193f8e58f267663d5da8e38045b000d0983ac08b84808de42af1a44963f63205
license    : BSD-3-Clause
component  : programming.haskell
summary    : Kan extensions, Kan lifts, various forms of the Yoneda lemma, and (co)density (co)monads
description: |
    Kan extensions, Kan lifts, various forms of the Yoneda lemma, and (co)density (co)monads
builddeps  :
    - haskell-cabal-install
    - haskell-adjunctions-devel
    - haskell-free-devel
rundeps    :
    - devel:
        - haskell-adjunctions-devel
        - haskell-free-devel
networking : yes
setup      : |
    # temporarily disable `fail` until next release fixes the check
    sed -i "60d" kan-extensions.cabal # fail
    sed -i "s|0.6|0.7|g" kan-extensions.cabal # containers + transformers-compat
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
