name       : haskell-kan-extensions
version    : '5.1'
release    : 2
source     :
    - http://hackage.haskell.org/package/kan-extensions-5.1/kan-extensions-5.1.tar.gz : 193f8e58f267663d5da8e38045b000d0983ac08b84808de42af1a44963f63205
license    : BSD-3-Clause
component  : programming.haskell
summary    : Kan extensions, Kan lifts, various forms of the Yoneda lemma, and (co)density (co)monads
description: |
    Kan extensions, Kan lifts, various forms of the Yoneda lemma, and (co)density (co)monads
builddeps  :
    - haskell-adjunctions
    - haskell-cabal-install
    - haskell-fail
    - haskell-transformers-compat
setup      : |
    sed -i "s|0.6|0.7|g" kan-extensions.cabal
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
